name: Model Training and Email Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_and_notify:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set up Google Credentials from Secrets
    - name: Set up Google Credentials
      run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

    # Step 5: Train the model (Replace this with your actual training script)
    - name: Train model
      run: |
        python train_model.py  # Replace with your model training script

    # Step 6: Send email notification
    - name: Send email notification
      run: |
        python scripts/send_email_oauth2.py --subject "Model Training Success" --message "The model training completed successfully."

    # Step 7: Clean up credentials file
    - name: Clean up credentials
      run: rm credentials.json
