name: Validation and Bias Check Pipeline

on:
  push:
    paths:
      - 'scripts/evaluation.py'
      - 'scripts/bias_evaluation.py'
      - 'scripts/question.xlsx'
      - 'scripts/bias_question.xlsx'

  workflow_dispatch:

jobs:
  validate_and_check_bias:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run validation script
        run: python scripts/evaluation.py

      - name: Run bias check script
        run: python scripts/bias_evaluation.py

      - name: Save results artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation-and-bias-results
          path: validation/